Feat OW-60 : 회원가입 추가
Goorm-OGJG/Web-IDE pull request #40
Opened 2023-09-25 03:45 UTC by Dongjin113

- [ ] 회원가입시 중복가입 확인
- [ ] 이메일 인증 확인
- [ ] 이메일 인증이후 30분 이내 가입 확인

2023-09-25 06:32 UTC, dunowljj requested changes

2023-09-25 06:32 UTC, dunowljj commented on back/src/main/java/com/ogjg/back/user/service/UserService.java
> +        }
두 에러 메시지의 의미가 구분하기 모호하단 생각이 들었어요. 에러 메시지를 좀 더 구체적으로 써주시면 좋을 것 같습니다!

2023-09-25 08:11 UTC, Dongjin113 commented on back/src/main/java/com/ogjg/back/user/service/UserService.java
> +        }
변경했습니다

2023-09-25 13:34 UTC, bstaran approved these changes
고생하셨습니다!! 👍

2023-09-26 09:17 UTC, dunowljj approved these changes
고생하셨습니다~

2023-09-26 09:17 UTC, dunowljj commented on back/src/main/java/com/ogjg/back/user/service/UserService.java
>       * */
@Transactional이 누락되어있습니다!

2023-09-26 11:40 UTC, dunowljj approved these changes

2023-09-26 13:43 UTC, Dongjin113 commented on back/src/main/java/com/ogjg/back/user/service/UserService.java
>       * */
수정했숨다

2023-09-26 13:44 UTC, merged